### PR TITLE
Using hitTest instead of pointInside

### PR DESCRIPTION
**Pull request by zhigang1992**
This fix the case where accessibility is broken, and only enabled when hover over links. 😄

### CODE REVIEW

**Comment by choefele** [comment]
Thanks for your PR. Could you please elaborate what would be the difference between using `hitTest` instead of `pointInside`? Is it that `hitTest` ignores hidden views? How is this related to accessibility?

Thanks again

**Comment by zhigang1992** [comment]
Somewhat similar/related to the post here

http://stackoverflow.com/questions/15033906/how-to-create-accessibilityframe-different-from-views-bounds

`pointInside` test will change the accessibility frame

**Comment by choefele** [comment]
Sorry, I still don't understand. How would I need to modify the example in this repo to check that `pointInside` fails and see that `hitTest` fixes this problem?

**Comment by zhigang1992** [comment]
Sorry, it's been a while. I don't remember what this change is for anymore. 🤦‍♂️ 

Anyway, thanks for an awesome project.

**Pull request closed without merging**
